services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - product-manager-api

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8099:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - product-manager-api

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3340:3306"
        networks:
            - product-manager-api
    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        depends_on:
            - mysql
        environment:
            PMA_ARBITRARY: 1
            PMA_VERBOSE: "${APP_NAME}"
            PMA_HOST: "${DB_HOST}"
            PMA_PORT: "${DB_PORT}"
            PMA_USER: "${DB_USERNAME}"
            PMA_PASSWORD: "${DB_PASSWORD}"
            UPLOAD_LIMIT: "20M"
        ports:
            - "8084:80"
        volumes:
            - .docker/phpmyadmin/data/sessions:/sessions
        networks:
            - product-manager-api
    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - product-manager-api
    # redis
    redis:
        image: redis:latest
        networks:
            - product-manager-api

networks:
    product-manager-api:
        driver: bridge